Repository Deltares/hydromt, pull requests merged in 2023-04, with the labels that each got.

#313 ENH: support data like objects in DataCatalog.get methods
  docs/changelog.rst
  hydromt/data_catalog.py
  tests/test_data_catalog.py
Labels: enhancement, DataCatalog & DataAdapters

#290 ENH: consistent raster.clip_mask and clip_geom methods
  hydromt/raster.py
  tests/test_raster.py
Labels: enhancement, RasterDataset

#315 small fix parsing paths in yml
  hydromt/config.py
Labels: bug
