Repository Deltares/hydromt, pull requests merged in 2023-10, with the labels that each got.

#531 Vector model updates
  docs/api.rst
  docs/changelog.rst
  docs/dev/plugin-quickstart.rst
  docs/dev/roadmap.rst
  docs/getting_started/installation.rst
  docs/user_guide/intro.rst
  docs/user_guide/model_overview.rst
  examples/working_with_models.ipynb
  examples/working_with_models_basics.ipynb
  examples/working_with_raster.ipynb
  hydromt/models/__init__.py
  hydromt/models/model_lumped.py
  hydromt/models/model_plugins.py
  hydromt/models/model_vector.py
  hydromt/vector.py
  pyproject.toml
  tests/conftest.py
  tests/test_api.py
  tests/test_cli.py
  tests/test_model.py
  tests/test_vector.py
Labels: Model

#489 Add support for multiple csv segmented by var
  hydromt/io.py
  tests/conftest.py
  tests/test_io.py
Labels: PR Waiting for Review

#534 Small Model updates
  docs/changelog.rst
  hydromt/models/model_api.py
  tests/test_model.py
Labels: Blocked PR

#595 Mesh model notebook
  .github/workflows/tests.yml
  docs/changelog.rst
  docs/getting_started/examples_index.rst
  docs/user_guide/intro.rst
  examples/data/mesh_model/mesh1d2d.nc
  examples/data/vito_reclass.csv
  examples/working_with_meshmodel.ipynb
  hydromt/models/model_mesh.py
  hydromt/workflows/mesh.py
Labels: PR Waiting for Review

#583 Pyogrio io
  docs/changelog.rst
  hydromt/gis_utils.py
  hydromt/io.py
  pyproject.toml
  tests/conftest.py
  tests/test_gis_utils.py
  tests/test_io.py
Labels: Bug

#622 move pyogrio to mandatory imports
  pyproject.toml
Labels: Bug

#621 Handle nodata data adapter
  docs/changelog.rst
  hydromt/data_adapter/dataframe.py
  hydromt/data_adapter/geodataframe.py
  hydromt/data_adapter/geodataset.py
  hydromt/data_adapter/rasterdataset.py
  hydromt/data_catalog.py
  hydromt/exceptions.py
  hydromt/nodata.py
  tests/test_data_adapter.py
Labels: Bug
